biolerplate_react_app
codesect/cs01-team-ada-05 pull request #2
Opened 2019-10-18 19:36 UTC by SanthoshBalagur

mistakenly added votingapp folder on it please remove that folder

2019-10-19 12:50 UTC, zsoltime requested changes
Please remove the unnecessary `votingapp` folder.

2019-10-19 16:12 UTC, SanthoshBalagur commented
removed voting app

2019-10-19 16:17 UTC, SanthoshBalagur commented
changed the d

2019-10-20 15:59 UTC, zsoltime approved these changes

2019-10-20 16:49 UTC, zsoltime approved these changes

2019-10-20 16:53 UTC, merged